[params]
  enableGitalk = true
[params.gitalk]  
    clientID = "[Client ID]" # [Client ID] 替换成你的Client ID
    clientSecret = "[Client Secret]" # [Client Secret] 替换成你的Client Secret
    repo = "{git-username}.github.io" # 你的Github个人主页
    owner = "{git-username}" # 你的 GitHub ID
    admin= "{git-username}" # Required. GitHub ID. Github repository owner and collaborators. (Users who having write access to this repository)
    
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.